apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- secrets.yaml
- postgres-statefulset.yaml
- postgres-service.yaml
- fhir-deployment.yaml
- fhir-service.yaml
- fhir-configmap.yaml
- dashboard-deployment.yaml
- dashboard-service.yaml
- metering-sidecar-deployment.yaml
- keycloak-deployment.yaml
- keycloak-service.yaml
- keycloak-configmap.yaml

# Made with Bob
